### PR TITLE
pass through more data from controller and map more explicitly in react

### LINKED ISSUE #207: Match days in New Zealand to correct year
Currently the order is being reversed

A/C

- [ ] test exists for an applicant with movements meaning they pass year 1,2,3, and fail year 4, 5 and that applicants days in new zealand exceed 260 for year 1,2,3 and is less than 260 for year 4,5

### PR DESCRIPTION
**Pull request by mischa-s**
Fix is done. Needs before merging:

- [x] update existing tests

closes #207

### CODE REVIEW

**Comment by danieljauch** [comment]
Would it be possible to change `yrNumber` to `yearNumber` or `yearNum` or something else? It seems hard to scan when everything else says `year` 😛 It's a pedantic thing, but it just kept catching me haha

**Comment by mischa-s** [comment]
> Would it be possible to change `yrNumber` to `yearNumber` or `yearNum` or something else? It seems hard to scan when everything else says `year`  It's a pedantic thing, but it just kept catching me haha

makes sense, done

File: app/controllers/clients_controller.rb [hunk 1]
```diff
@@ -23,8 +23,8 @@ def eligibility
     render json: {
       requested_date => {
         'meetsMinimumPresence' => @service.meets_minimum_presence_requirements[requested_date],
-        'last5Years' => @service.enough_days_by_rolling_year.values,
-        'daysInNZ' => @service.days_by_rolling_year.values
+        'last5Years' => @service.enough_days_by_rolling_year,
```
Comment (Br3nda) [inline app/controllers/clients_controller.rb]: nice!
