### PR TITLE
Fix/change selected date to rolling year

### LINKED ISSUE #321: Make sure UI uses correct date
Currently the UI uses the wrong date as shown in the screenshots on #225

A/C
- For application of 28 February 2017 should check from 28 February 2016 to 27 February 2017

### PR DESCRIPTION
**Pull request by mischa-s**
close #321

### CODE REVIEW

File: app/javascript/bundles/Presence/components/PresenceDates.jsx [hunk 1]
```diff
@@ -38,12 +38,14 @@ export default class PresenceDates extends React.Component {
   render() {
     const {
       isEligible,
-      selectedDate,
+      endOfRollingYear,
```
Comment (Br3nda) [inline app/javascript/bundles/Presence/components/PresenceDates.jsx]: Nice
