### PR TITLE
Fix logout links

### LINKED ISSUE #100: Turn off sign ups
we can't allow anonymous people to sign up to the app -- Turn off this functionality, and make some tests to check it doesn't get turned on

### LINKED ISSUE #101: Signout link doesn't work

### PR DESCRIPTION
**Pull request by Br3nda**
fixes #101

### CODE REVIEW

File: config/initializers/devise.rb [hunk 1]
```diff
@@ -251,7 +251,7 @@
   # config.navigational_formats = ['*/*', :html]
 
   # The default HTTP method used to sign out a resource. Default is :delete.
-  config.sign_out_via = :get
+  config.sign_out_via = :delete
```
Comment (dlouise64) [inline config/initializers/devise.rb]: @Br3nda Ahh yes I remember having to do this at one point. 👍
